# Change these first
owner: rodseb # Your GitHub organization or username, where this repository lives
repo: Status-services # The name of this repository

sites:
  - name: Host
    url: $SECRET_SITE
  - name: Site web
    url: https://spm-corp.fr

   ##-- Services assetto corsa competizion --##
  - name: ACC Tracker
    url: http://45.155.169.5:51051
    ## ACC Manager
  - name: Serveur 1
    url: http://45.155.169.5:9501
  - name: Serveur 2
    url: http://45.155.169.5:9502
  - name: Serveur 3
    url: http://45.155.169.5:9503
  - name: Serveur 4
    url: http://45.155.169.5:9504
  - name: Serveur 5
    url: http://45.155.169.5:9505
  - name: Serveur 6
    url: http://45.155.169.5:9506
  - name: Serveur 7
    url: http://45.155.169.5:9507
  - name: Serveur 8
    url: http://45.155.169.5:9508

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status-acc.spm-corp.fr
  # baseUrl: /your-repo-name
  logoUrl: https://spm-corp.fr/wp-content/uploads/2022/03/cropped-cropped-Logo_transparent-300x162-1.png
  name: Status Servive SPM
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
